### ISSUE TITLE
modename 

### ISSUE THREAD

**Issue by sfischme** [wasamasa/firestarter#1]
firestarter is not properly displayed in the modeline

![selection_001](https://cloud.githubusercontent.com/assets/250263/7106063/2cdc3aa6-e103-11e4-9d09-e10f75059496.png)

**Comment by wasamasa** [comment]
If you can't see [this](http://www.fileformat.info/info/unicode/char/1f525/index.htm) either, install a proper font, like [Symbola](http://users.teilar.gr/~g1951d/) or [Quivira](http://www.quivira-font.com/).  Alternatively, customize `firestarter-lighter` before enabling the mode.

**Comment by wasamasa** [comment]
Investigation on `#emacs` made clear that Emacs (at least the version with the `xft` backend) does not support automatic font fallback.

The following code would do the trick:

``` elisp
(set-fontset-font "fontset-default" nil "Symbola" frame 'append)
```
