### ISSUE TITLE
Add a %() sequence to splice elisp into the command.

### ISSUE THREAD

**Issue by Fuco1** [wasamasa/firestarter#12]
Useful when I want to transform current buffer name to test file name or something similar.

**Comment by wasamasa** [comment]
Hm, this wouldn't match the existing percent escape sequences as they're always of the `%x` format.  Other problems are how you'd match that (greedy? non-greedy? parsing s-expressions with a stack?) and how it would look like for common cases (variable? single expression? multiple expressions?).

I'm inclined to believe that if the built-in escapes are not enough, it would be better to execute elisp directly.  You can access the functions that are used for executing strings, so it should be okayish for that purpose.

**Comment by Fuco1** [comment]
org and interactive replace and yasnippet do this, I don't know how but it's super handy :P  Think templating.

The () after the % would be a form, so you would grab a balanced expression.

The problem with elisp is that I would need to rewrite all the process handling.  Then maybe add a syntax for `firestarter` where I give it elisp to _generate_ the command string to run.  That way I can reuse firestarter's process handling and have the power of elisp at the same time.

**Comment by wasamasa** [comment]
From what I can tell in `replace.el`, it scans for a comma, then invokes `read-from-string` and replaces that part of the string with the form. So, nothing wild here.

**Comment by wasamasa** [comment]
Does this look OK to you?

``` elisp
(defvar my-magic-string-starter
  (rx (or (and bos "%(")
          (and (not (any "%")) "%("))))

(defun my-eval-magic-string (string)
  (if (string-match my-magic-string-starter string)
      (let* ((beg (1- (match-end 0)))
             (result (read-from-string string beg))
             (form (car result))
             (end (cdr result)))
        (format "%s%s%s"
                (substring string 0 (1- beg))
                (eval form)
                (substring string end)))
    string))

(my-eval-magic-string "%(+ 1 1)") ;=> "2"
(my-eval-magic-string "%%(+ 1 1)") ;=> "%%(+ 1 1)"
(my-eval-magic-string "foo: %(+ 1 1)") ;=> "foo: 2"
```

I'm less sure on how to handle errors (like, unbalanced forms).  Currently you get the infamous "End of file during parsing".  Another problem with this implementation is that it replaces exactly one match, but that can be rectified easily.

**Comment by Fuco1** [comment]
would it be possible to run the normal replacement first? `%b` should turn into buffer name in `%(concat %b "-test")`.  User might possibly quote the `%b`, dunno.

**Comment by wasamasa** [comment]
That should work if you apply the currently done formatting first, then the code outlined above...

**Comment by Fuco1** [comment]
Let's do this :) I would go for all matches not just the first one, seems more logical and consistent.

**Comment by wasamasa** [comment]
Hm, I've tried your more realistic test and found problems:
- `format-spec` will not accept a format string with `%(` in it.  It is written to throw an error if there's a format spec character that's not a letter.
- If you work around this by escaping the percentage character (blech), the result of the substitution is `%(concat firestarter.el \"-test\")` which would error out as argument to the above example function

So, what now?  Escaping more stuff?  Writing our own formatting function?  Both?

**Comment by Fuco1** [comment]
Well you need to put the filename token into quotes manually I guess.  

```
(my-eval-magic-string "%(concat \"firestarter.el\" \"-test\")")
```

works fine.  So you would write `"%(concat \"%b\" \"-test\")")`, it would first replace `%(` with `\%(` and then run the above on the result.  Alternatively, `%b` could be replaced with quoted string automatically when inside `%(..)` sequence.  Hm... which would require another preprocess to put it there before you run `format-spec` on it.

**Comment by Fuco1** [comment]
Obviously emacs `query-replace-regexp` uses some sort of dark magic for this: `query-replace-compile-replacement`

**Comment by wasamasa** [comment]
Yeah, no, I can't justify the costs for this feature, given the size of the package.
