### ISSUE TITLE
Allow more than one handler

### ISSUE THREAD

**Issue by Fuco1** [wasamasa/firestarter#14]
The more I use `firestarter` the less ideal I find the interface.

Currently we can do these things: symbol, list (to eval), function, shell command.

But I almost never do "one thing".  I want to run gtags, run tests, update the documentation, regenerate deploy scripts... (whatever).

Many of these actions are the same for multiple projects/languages (compile/gtags and similar universal interfaces).  It would be much more pleasant to be able to just push to a hook, like `after-save-hook`, which would be controlled by `firestarter-mode`.

In other words, let's make the interface composable.

Firestarter should have its own "hook" instead of the `firestarter` property where I would push actions (be it code, strings, shell snippets, whatever) and run it one by one as now.  This will allow me to push to the hook just the things I want to do (for example in the mode init hook) and reuse existing "snippets".  We can then build a library of those for people to reuse.

For example I wrote a snippet

``` elisp
(defun my-php-update-gtags ()
  "Update gtags for current file upon saving."
  (start-file-process
   "global--single-udpate"
   (get-buffer-create "*async update tags*")
   "global"
   "--single-update"
   (my-php-local-file-name
    (expand-file-name (buffer-file-name)))))
```

and then realized there is absolutely nothing php related here... you can use this anywhere.  But if you run your own `firestarter` in c# (for example a string to run nunit tests) you can't easily include this.  You would need to write a wrapper function for your shell command, then attach this piece of code, then set this new function to `firestarter`.  Every time you would want to add something, you would need to edit your `my-csharp-firestarter-command`.

The above situation is real and actually prompted me to propose this.

The cool thing with `add-hook` is this:

``` elisp
(defvar foo-hook nil)

(add-hook 'foo-hook "adsasd")
(add-hook 'foo-hook 'asda)
```

You can push any values, not just functions... so the interface from user's point of view is just as a normal hook.  Only on firestarter's side we can't use `run-hook` but some custom code to decide what to do with the values and should be hopefully quite simple.

What do you think?

**Comment by wasamasa** [comment]
I'm not convinced of this being worth breaking backward compatibility.  How exactly would you implement the README examples if all you had was a hook?  Adding an eval block to each file that adds the types buffer-locally to the hook?

**Comment by Fuco1** [comment]
You can run the `firestarter` thing as well.  The proposal basically means turing it into a list of things.  But that is problematic as you can have a list value already, and you wouldn't know what to do in that case.  Which is why the other is called `-hook`.

I wouldn't configure it in an eval block but on the init hooks for the modes I'm interested in.  Right now I push things to `after-save-hook` but that has other problems, like inconvenient handling of shell commands etc.

**Comment by wasamasa** [comment]
I've pondered about this again and decided against it.  But feel free to do this in another package.  After all, firestarter is tiny, so there's not much cost involved, even if you start from scratch...
