### ISSUE TITLE
Notification when command has finished

### ISSUE THREAD

**Issue by clearmisp** [wasamasa/firestarter#15]
Is it possible to configure firestarter so that one receives a notification when the command has finished? I have firestarter setup so that I trigger it manually using M-x firestarter and firestarter writes all its output to the *firestarter* buffer. To determine when the command has finished I have to repeatedly check if the firestarter buffer has been created, if so I have to check its content. Is there another way to determine when the firestarter command has finished?

**Comment by wasamasa** [comment]
Sure, that can be done by customizing `firestarter-reporting-functions`.  The default happens to use one that writes things to a buffer, but there's no reason why you couldn't add something of your own sending a notification.
