### ISSUE TITLE
Error with start-process

### ISSUE THREAD

**Issue by ccakes** [wasamasa/firestarter#16]
I followed the guide [here](https://www.diegoberrocal.com/blog/2015/12/04/using-rsync-when-tramp-is-too-much/) to try and use firestarter to rsync a project to a remote server on save however I'm getting an error which I believe is related to how emacs is handling the command.

```
Unknown filter rule: `':- .gitignore'
rsync error: syntax or usage error (code 1) at exclude.c(927) [client=3.1.3]
```

```
;; .dir-locals.el
((nil
  .
  ((firestarter . (let* ((rsync--obey-gitignore t)
                         (rsync--exclude-git t)
                         (args `("-aP"
                                 "--delete"
                                 ,(when (and rsync--obey-gitignore
                                             (file-exists-p ".gitignore"))
                                    "--filter=':- .gitignore")
                                 ,(when rsync--exclude-git
                                    "--exclude='.git/'")
                                 ,(projectile-project-root)
                                 "me@192.168.0.1:project/")))
                    (apply 'start-process "rsync" "*rsync-firestarter*" "rsync" args))))))
```

The generated command works fine directly on the CLI. I'm very new at Elisp so just looking for a hand on how to go about troubleshooting/fixing this. I'm on macOS, I get the same error with both built-in rsync and rsync from homebrew.

**Comment by wasamasa** [comment]
I have my doubts the author ever proof-read their own blog post, this function cannot possibly work for anyone. The syntax is fine on the CLI because the shell processes the quoting, however Emacs takes the `"--filter=':- .gitignore'"` part literally (which you've copy-pasted incorrectly by omitting the closing quote). Try using `"--filter=:- .gitignore"` instead.
