### ISSUE TITLE
How to make firestarter to auto start compile command without putting anything in file

### ISSUE THREAD

**Issue by tuhdo** [wasamasa/firestarter#4]
Similar to [my answer](http://emacs.stackexchange.com/a/10684/200) on SE.

I don't want to put anything in my file but just my Emacs configuration. Currently I added `my-customize-firestarter` to a major mode hook (with `firestarter` enabled) but it seems to do nothing.

**Comment by wasamasa** [comment]
I find this a bit hard to believe.

Here's a minimal working example I've whipped up:

``` elisp
(package-initialize)
(firestarter-mode)

(defun my-customize-firestarter ()
  (setq firestarter 'compile))
(add-hook 'emacs-lisp-mode-hook 'my-customize-firestarter)
```

Saving this as `~/.emacs` gives me `compile` when using `M-: firestarter` in the `*scratch*` or any other Emacs Lisp buffer. It also prompts me for a compilation command upon save. How does the example work for you?

**Comment by tuhdo** [comment]
Hmm I'm using Spacemacs and it does nothing. Not sure what happened, even after trying `emacs-lisp-mode` and `c-mode`.

I will try with stock Emacs later.

**Comment by wasamasa** [comment]
@tuhdo Any updates on this yet?

**Comment by tuhdo** [comment]
Hmm it works now. Not sure why it didn't before.
