### ISSUE TITLE
firestarter gets trigered in magit buffers

### ISSUE THREAD

**Issue by CestDiego** [wasamasa/firestarter#6]
every time I commit or stash opened buffers.

**Comment by wasamasa** [comment]
Ouch. Must be their change about reverting buffers which triggers way too often. Can you provide a minimal self-contained example of your config, what exactly you're doing and the expected results compared to the actual ones?

**Comment by wasamasa** [comment]
Yup, that smells like a major bug, [I'm currently working on aria2](https://github.com/tatsuhiro-t/aria2/pull/395) and every time I expand a section in my git status, I see reverting messages flash by like crazy. Did you consider giving magit's `next` branch a try to see whether that fixes things?

**Comment by CestDiego** [comment]
ok will give a try.

**Comment by wasamasa** [comment]
https://github.com/magit/magit/issues/1856

**Comment by wasamasa** [comment]
As I can no longer reproduce this on the `next` branch (which will soon turn into a regular release and be on `HEAD`) and there's nothing this package could do about it anyways for earlier magit versions, I'm closing this.

**Comment by CestDiego** [comment]
Gr8 thx, btw do you happen to know how much time will pass until we get to the `next` branch?

**Comment by wasamasa** [comment]
https://github.com/magit/magit/issues/1645
