### ISSUE TITLE
Post-firestarter-command hook

### ISSUE THREAD

**Issue by swsnr** [wasamasa/firestarter#8]
Would you mind to add a hook that runs after every command run by firestarter, and gets the result of the command as argument?

I'd like to use this hook to implement a custom mode line reporting for firestarter commands…

**Comment by wasamasa** [comment]
What exactly do you mean by result, the return code, the textual output of the command or both?

**Comment by swsnr** [comment]
@wasamasa For my purposes the exit code would be sufficient.  

Thinking of it, you could probably also just pass the process object to the hook.  Any hook function can then take whatever information it needs from that object (e.g. process status, exit code, etc.)

**Comment by swsnr** [comment]
By the way, speaking of the process object, is there a reason why you use a dedicated buffer local variable for the output of the process?  In Flycheck I put the output into a process property, and if you did that and passed the process object to the hook, hook functions could also get hold of the process output.  And you'd have one buffer local variable less, and the less global state, the better :)

**Comment by wasamasa** [comment]
Thanks for the analysis. I've looked at the respective parts of Flycheck you were speaking of and came to the conclusion that I should be able to get rid of a few buffer-local variables by attaching more properties to the process. While I'm at it, I could get rid of the buffer tracking as it was only necessary to retrieve buffer-local values safely.

An abnormal hook (something like `firestarter-reporting-functions`) sounds like a good idea, I'd run it as suggested with the process object as argument in the sentinel function. Maybe I'll even make the current reporting the default value of that hook, that way you'd both have an example of its usage and could yank this functionality out if you wish to.

**Comment by swsnr** [comment]
@wasamasa That would be a great!
